### ISSUE TITLE
Unable to detect MPL20 in markdown format

### ISSUE THREAD

**Issue by client9** [ryanuber/go-license#14]
You might recognize this one :-)

https://github.com/mitchellh/packer/blob/master/LICENSE

there are a number of others:

https://github.com/client9/gosupplychain/blob/master/reports/github-users.md#mitchellh

**Comment by satreix** [comment]
The following solves the issue.

```diff
- 	case scan(comp, "mozilla public license, version 2.0"):
+	case scan(comp, "mozilla public license version 2.0"):
```

We might want to go from using litteral license extracts to using looser regex or fuzzy lookup with a short distance.

**Comment by ryanuber** [comment]
#15 fixes this by normalizing the text a bit more. I plan on bringing that in this week. Fixing all white space and/or newlines to a single space, lowercasing everything, and stripping quotes and other punctuation solves the 95% case without getting too complicated. Also FWIW, I just merged another PR that fixes this exact issue on master.
