### ISSUE TITLE
case-insenstive comparison: License.txt

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ryanuber/go-license#8]
I was looking at `GuessFile` method and it looks like if the license file is

*  ` License.txt` (for instance https://github.com/dotnet/roslyn/blob/master/License.txt)
* or `LICENSE.TXT` (https://github.com/dotnet/coreclr/blob/master/LICENSE.TXT)

it wouldn't match... (I know, microsoft people, right?..)

Perhaps if we do the string comparison case-insensitive, that could also help eliminating the duplication going on at `DefaultLicenseFiles` variable. 

What do you think @ryanuber ?

**Comment by ryanuber** [comment]
Makes sense to me! I agree it would be nicer to just `strings.ToLower()` everything before comparing.

**Comment by client9** [comment]
I'm going to work on a pull request for this one, minus objections.

**Comment by client9** [comment]
see #9 pull request

**Comment by client9** [comment]
Ok @ryanuber should be good to take a look in #9  thx to @ahmetalpbalkan  I added some more testing.

**Comment by client9** [comment]
This can be closed
